### ISSUE TITLE
Wrong command is shown in the Installation of grImport2

### ISSUE THREAD

**Issue by qifei9** [sjp/sjp-site#1]
In https://sjp.co.nz/projects/grimport2, Installation part, the command 
```
> devtools::install_github("sjp/grConvert")
```
 should be 
```
> devtools::install_github("sjp/grImport2")
```

**Comment by sjp** [comment]
Thanks!

I'll update the site sometime today but the repo will take more time.

**Comment by sjp** [comment]
The website is now corrected, the commit fixing the repo is still pending.
